export const TYPES = {
  PENDING: 'FETCH_PENDING_TODOS',
  FIND: 'FETCH_SUCCESS_TODOS',
  LIST: 'FETCH_LIST_SUCCESS_TODOS',
  UPDATE: 'FETCH_UPDATE_SUCCESS_TODOS',
  DELETE: 'FETCH_DELETE_SUCCESS_TODOS',
  CREATE: 'FETCH_CREATE_SUCCESS_TODOS',
  ERROR: 'FETCH_ERROR_TODOS',
};
